# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField()),
                ('uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
