# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_num',
            new_name='read_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislike_num',
        ),
    ]
