# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180413_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_time',
            field=models.DateTimeField(),
        ),
    ]
