# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
